import { GoogleGenAI, mcpToTool } from "@google/genai";
import type { GenerateContentResponse } from "@google/genai";
import type { Client } from "@modelcontextprotocol/sdk/client";

class geminiService {
  private static instance: geminiService;
  private readonly modelName: string;
  private readonly apiKey: string;
  private readonly ai: GoogleGenAI;

  constructor(modelName = process.env.GEMINI_MODEL) {
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey) {
      throw new Error("API key is required");
    }

    if (!modelName) {
      throw new Error("Model name is required");
    }

    this.modelName = modelName;
    this.apiKey = apiKey;

    this.ai = new GoogleGenAI({ apiKey: this.apiKey });
  }

  static getInstance(modelName?: string): geminiService {
    if (!geminiService.instance) {
      geminiService.instance = new geminiService(modelName);
    }
    return geminiService.instance;
  }

  async generateResponse(prompt: string): Promise<string> {
    try {
      const response = await this.ai.interactions.create({
        model: this.modelName,
        input: prompt,
      });
      return response.output_text || "No response generated from Gemini API";
    } catch (error: any) {
      console.error("Error generating response from Gemini API:", error);
      throw new Error("Failed to generate response from Gemini API");
    }
  }
  async generateResponseWithTools(
    prompt: string,
    mcpClient: Client,
  ): Promise<string> {
    try {
      const response = await this.ai.models.generateContent({
        model: this.modelName,
        contents: [
          {
            role: "user",
            parts: [
              {
                text: prompt,
              },
            ],
          },
        ],
        config: {
          systemInstruction: {
            role: "model",
            parts: [
              {
                text: "You are an AI assistance specialized in E-commerce data (orders and customers) and weather data too. When a customer ask about orders or customers or weather information,use the provided tools **if  the question is unrelated to your tools , answer using your intrinsic knowledge . **Be concise do not mention the tools where used unless asked ",
              },
            ],
          },
          tools: [mcpToTool(mcpClient)],
        },
      });

      return this.extractResponseText(response);
    } catch (error: any) {
      console.error("Error generating response from Gemini API:", error);
      throw new Error("Failed to generate response from Gemini API");
    }
  }

  extractResponseText(response: GenerateContentResponse): string {
    const candidate = response?.candidates?.[0];

    if (!candidate) return "";

    //step 1: find the primary text part in the model's final response
    const textPart = candidate.content?.parts?.find((part) => part.text);

    if (textPart && textPart.text) {
      return textPart.text.trim();
    }

    //step2 : fallback for debugging
    const structuredContent = candidate.content?.parts
      ?.find((part) => part.functionResponse?.response?.structuredContent)
      ?.functionResponse?.response?.structuredContent;

    if (structuredContent) {
      return (
        "Tool executed successfully but no natural language summary provided Raw data:\n" +
        JSON.stringify(structuredContent, null, 2)
      );
    }

    return "No response was generated by the LLM Model";
  }

  async generateEmbeddings(
    data: string | string[],
    taskType = "RETRIEVAL_QUERY",
  ) {
    try {
      const response = await this.ai.models.embedContent({
        model: "gemini-embedding-001",
        contents: data,
        config: { taskType: taskType },
      });

      const embeddings = response.embeddings?.map((e) => e.values) ?? [];
      return embeddings;
    } catch (error) {
      console.error("Error generating embedding from Gemini API:", error);
      throw new Error("Failed to generate embedding from Gemini API");
    }
  }
}

export const GEMINI = geminiService.getInstance();
